// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf53-mk7iQQau4HhhMspZxkz1_MZZ507A',
    appId: '1:106680220330:web:ed3988b8e20027e0f0aed3',
    messagingSenderId: '106680220330',
    projectId: 'bizmapcabuyao',
    authDomain: 'bizmapcabuyao.firebaseapp.com',
    storageBucket: 'bizmapcabuyao.firebasestorage.app',
    measurementId: 'G-QC02T69FND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_iZbmIQPysHOkSDc14QyG-y05P9lq4SI',
    appId: '1:106680220330:android:e99df32476c7bc8af0aed3',
    messagingSenderId: '106680220330',
    projectId: 'bizmapcabuyao',
    storageBucket: 'bizmapcabuyao.firebasestorage.app',
  );
}
